### ISSUE TITLE
Compression doesn't work for a simple file

### ISSUE THREAD

**Issue by gettalong** [laurentmmeyer/ghostscript-pdf-compress.wasm#1] opened 2024-05-03 21:51 UTC
I tried the compression tool at www.saferpdf.com with one of my test files and the result was a file that was nearly double in size.

Here is the file in question: [a.pdf](https://github.com/laurentmmeyer/ghostscript-pdf-compress.wasm/files/15205289/a.pdf)

**Comment by laurentmmeyer** [comment] 2024-05-03 22:06
Hey @gettalong !

Thanks a lot for the report! It seems that we have an issue with already very optimized PDF. I believe that this is caused by Ghostscript not being extremely good with the XRef and Stream objects. It seems to be resolved in 10.03 but I didn't port it to WASM just yet.

I will give a shot to qpdf as well; I keep you updated!

**Comment by laurentmmeyer** [comment] 2024-05-04 18:46
I updated [https://saferpdf.com](https://saferpdf.com) and was able to reduce a.pdf by 7% with qpdf 🎉

**Closed as completed by laurentmmeyer** 2024-05-04 18:46 UTC

**Comment by gettalong** [comment] 2024-05-04 22:47
Yes, qpdf usually compresses better and a ~7% reduction for that file is what I would expect, see https://hexapdf.gettalong.org/documentation/benchmarks/optimization.html.
